# Generated by Django 5.2.8 on 2026-02-14 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='invite_code',
        ),
        migrations.AddField(
            model_name='chapter',
            name='active_invite_code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='chapter',
            name='nm_invite_code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
