# Generated by Django 5.2.8 on 2026-02-16 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_chapter_invite_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='can_manage_nm_points',
            field=models.BooleanField(default=False, help_text='Can manage and edit New Member points.'),
        ),
    ]
