# Generated by Django 5.2.8 on 2025-12-28 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='pledge_semester',
            field=models.CharField(blank=True, choices=[('Fall', 'Fall'), ('Spring', 'Spring')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='pledge_year',
            field=models.IntegerField(blank=True, help_text='e.g. 2025', null=True),
        ),
    ]
