# Generated by Django 6.0 on 2026-01-12 20:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Reimbursement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="What will you be buying and for what reason?"
                    ),
                ),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING_SPENDING", "Pending Approval to buy"),
                            ("APPROVED_BUY", "Approved to buy"),
                            ("REJECTED_BUY", "Rejected to buy"),
                            ("PENDING_REIMBURSEMENT", "Pending Reimbursement"),
                            ("APPROVED_REIMBURSEMENT", "Approved Reimbursement"),
                            ("REJECTED_REIMBURSEMNET", "Rejected Reimbursement"),
                        ],
                        max_length=30,
                    ),
                ),
                ("receipt_image", models.ImageField(null=True, upload_to="receipts/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "requestor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
