# Generated by Django 5.2.8 on 2025-12-27 01:49

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_announcement'),
        ('users', '0002_customuser_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='housepoint',
            name='approved',
        ),
        migrations.RemoveField(
            model_name='housepoint',
            name='reason',
        ),
        migrations.AddField(
            model_name='housepoint',
            name='assigned_approver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='points_to_approve', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='housepoint',
            name='chapter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='house_points', to='users.chapter'),
        ),
        migrations.AddField(
            model_name='housepoint',
            name='date_for',
            field=models.DateField(default=django.utils.timezone.now, help_text='When did this happen?'),
        ),
        migrations.AddField(
            model_name='housepoint',
            name='feedback',
            field=models.TextField(blank=True, help_text='Reason for rejection or counter-offer details.'),
        ),
        migrations.AddField(
            model_name='housepoint',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('COUNTERED', 'Counter-Offer Made')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='housepoint',
            name='submitted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='points_submitted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='housepoint',
            name='description',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='housepoint',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points_received', to=settings.AUTH_USER_MODEL),
        ),
    ]
