# Generated by Django 6.0 on 2026-01-12 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0003_reimbursement"),
    ]

    operations = [
        migrations.AddField(
            model_name="reimbursement",
            name="venmo_id",
            field=models.CharField(max_length=250, null=True),
        ),
    ]
