# Generated by Django 5.2.8 on 2025-12-27 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_remove_housepoint_approved_remove_housepoint_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='housepoint',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
