# Generated by Django 6.0 on 2026-01-12 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0004_reimbursement_venmo_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="reimbursement",
            name="title",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
